const data = [
  {
    id: "cement",
    name: "OPC Cement",
    quality: "Grade 53 OPC",
    description:
      "Premium Ordinary Portland Cement sourced from certified manufacturers. Ideal for foundations, columns, and all structural work.",
    price: 750,
    unit: "per 50kg bag",
    image: "home/featured/cement.png",
    company: "Ghar Sansar",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "rebar",
    name: "Steel Rebars",
    quality: "TMT Fe500",
    description:
      "High-strength Thermo-Mechanically Treated (TMT) rods for reinforced concrete work. Durable and corrosion-resistant.",
    price: 120,
    unit: "per kg",
    image: "product/bars.png",
    company: "GS",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "tiles",
    name: "Ceramic Floor Tiles",
    quality: "Glossy Finish",
    description:
      "Premium ceramic tiles suitable for floors and walls. Easy to clean, durable, and available in multiple designs.",
    price: 95,
    unit: "per sq. ft",
    image: "home/featured/tiles.avif",
    company: "Delight",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "paint",
    name: "Exterior Wall Paint",
    quality: "Weather Resistant",
    description:
      "High-quality exterior paint that withstands sun, rain, and dust. Long-lasting and vibrant colors.",
    price: 3200,
    unit: "per 20L bucket",
    image: "home/featured/paints.webp",
    company: "Ghar Sansar",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "wood",
    name: "Timber Planks",
    quality: "Seasoned Hardwood",
    description:
      "High-quality hardwood planks suitable for furniture, flooring, and structural purposes.",
    price: 1250,
    unit: "per cubic ft",
    image: "product/planks.jpg",
    company: "GS",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "pvc-pipes",
    name: "PVC Pipes",
    quality: "Durable & Lightweight",
    description:
      "High-quality PVC pipes for water supply and plumbing. Corrosion-resistant and easy to install.",
    price: 90,
    unit: "per meter",
    image: "home/featured/pipes.jpeg",
    company: "Delight",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "doors",
    name: "Wooden Doors",
    quality: "Solid Teak Wood",
    description:
      "Premium solid panel wooden doors. Perfect for bedrooms, entrance, and interior partitions.",
    price: 8500,
    unit: "per door",
    image: "home/doors.jpg",
    company: "Ghar Sansar",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "windows",
    name: "Aluminium Windows",
    quality: "Sliding Glass",
    description:
      "Lightweight and durable aluminium windows with smooth sliding mechanism and premium finish.",
    price: 450,
    unit: "per sq. ft",
    image: "product/windows.jpeg",
    company: "GS",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "roofing",
    name: "Corrugated Roofing Sheets",
    quality: "Galvanized Steel",
    description:
      "Durable roofing sheets suitable for homes, sheds, and commercial buildings. Resistant to weather and corrosion.",
    price: 2200,
    unit: "per sheet",
    image: "product/roof.jpeg",
    company: "Delight",
    rating: 4.7,
    inStock: true,
  },
];

export default data;
